services:

  hotword:
    build: .
    container_name: hotword
    hostname: hotword
    ports:
      - "5600:5600"
    restart: on-failure:3
    devices:
      - "/dev/snd"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    networks:
      - speak_io_net

networks:
  speak_io_net:
    driver: bridge
